### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by Mizuki-hhh** [Mizuki-hhh/furima-33010#10]
#URL
https://furima-33010.herokuapp.com/

#Basic認証のIDとパスワード
ID：furima
パスワード：3333

#出品者用のメールアドレスとパスワード
メールアドレス：higashi@higashi
パスワード：higashi3

#購入者用のメールアドレスとパスワード
メールアドレス：test@test
パスワード：testtest3

#購入用カードの番号・期限・セキュリティコード
番号：4242424242424242（16桁）
期限：3/23（登録時より未来）
セキュリティコード：123

**Comment by naru6117** [comment]
ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）
![最終課題終了_おめでとう画像](https://user-images.githubusercontent.com/49669977/103143946-d8d36880-4763-11eb-98e9-2c874ccdc1ae.png)


**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願いいたします。**

**Comment by Mizuki-hhh** [comment]
ご確認いただき、ありがとうございます！！
これから追加実装等頑張ってまいります！
